config/routes.rb
Rails.application.routes.draw do

  get "ajax/accounts"

  resources :properties do
    resources :transactions
  end

  devise_for :users

  root 'properties#index'

end

app/models/property.rb
class Property < ActiveRecord::Base
  validates :nickname, :presence => true
  validates :description, :presence => true
  validates :address, :presence => true

  belongs_to :user

  has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates :account, :presence => true
  validates :income, :expense, :miscellaneous,
            :presence => true,
            :numericality => true,
            :format => { :with => /\A(-)?\d{1,8}(\.\d{0,2})?\z/ }

  belongs_to :property
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties, dependent: :destroy
  has_many :transactions, through: :properties
end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController

  def accounts
    if params[:term]
      puts "==============================================================="
      puts "params[:term] = #{params[:term]}"
      puts "==============================================================="
      like = "%".concat(params[:term]).concat "%"
      transactions = current_user.transactions.select(:account).where("account like ?", like).distinct.limit 5
    else
      puts "==============================================================="
      puts "params = #{params}"
      puts "==============================================================="
      transactions = current_user.transactions.select(:account).distinct.limit 5
    end

    list = transactions.map { |transaction| Hash[account: transaction.account] }

    puts "================================================================="
    puts "list = #{list}"
    puts "================================================================="

    render json: list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.where(:user_id => current_user.id)
    @transactions = current_user.transactions

    income = @transactions.sum :income
    expense = @transactions.sum :expense
    miscellaneous = @transactions.sum :miscellaneous

    @summation = Hash[
      income: income,
      expense: expense,
      miscellaneous: miscellaneous,
      overall: (income + miscellaneous) - expense
    ]
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: PropertiesDatatable.new(view_context) }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @summation = Hash.new
    @summation[:income] = @property.transactions.sum :income
    @summation[:expense] = @property.transactions.sum :expense
    @summation[:miscellaneous] = @property.transactions.sum :miscellaneous
    @summation[:overall] = (@summation[:income] + @summation[:miscellaneous]) - @summation[:expense]

    respond_to do |format|
      format.html { render action: 'show'}
      format.json { render json: TransactionsDatatable.new(view_context, @property) }
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
    @property.user_id = current_user.id
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:user_id, :nickname, :description, :address)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.property_id = params[:property_id]

    set_date_time
  end

  # GET /transactions/1/edit
  def edit
    set_date_time
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to [@transaction.property], notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        set_date_time
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to [@transaction.property], notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        set_date_time
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def set_date_time
      current_time = if @transaction.date
                       @transaction.date.to_s.split("-")
                     else
                       Time.now.to_s.split(" ")[0].split("-")
                     end

      @current_year = current_time[0].to_i
      @current_month = current_time[1].to_i
      @current_day = current_time[2].to_i

      @possible_years = (@current_year - 5)..(@current_year + 5)
      @months_of_year = %w(January February March April May June July August September October November December)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:property_id, :account, :date, :income, :expense, :miscellaneous, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-success"
      when :warn then "alert alert-warning"
      when :info then "alert alert-info"
      else "alert alert-danger"
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || 'Property Ledger' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to properties_path, { id: 'logo' } do %>
            <h1>Property Ledger</h1>
        <% end %>
        <nav>
          <ul class="nav nav-pills pull-right">
            <% if user_signed_in? %>
                <li><%= link_to 'List Properties', properties_path %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
            <%# FIXME: This is commented out because I don't know it I will eventually. %>
            <!--<li><%# link_to "List Transactions", { controller: 'transactions', action: 'index' } %></li>-->
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <% flash.each do |name, msg| %>
        <div class="<%= flash_class name %>">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= msg %>
        </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_for [@property], :html => { :class => "form-horizontal" } do |f| %>
    <% if @property.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

          <ul>
            <% @property.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel-body">
      <%= f.hidden_field :user_id %>
      <div class="field form-group">
        <%= f.label :nickname, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :nickname, :class => 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :description, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :description, :class => 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :address, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :address, :class => 'form-control' %>
        </div>
      </div>
    </div>

    <div class="panel-footer">
      <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit nil, { :class => 'btn btn-primary' } %>
        </div>
      </div>
    </div>
<% end %>

app/views/properties/edit.html.erb
<% @title = "Edit Property" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Editing property</h1>
  </div>

  <%= render 'form' %>
</div>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to 'Show', @property %></li>
  <li><%= link_to 'Back', properties_path %></li>
</ul>

app/views/properties/index.html.erb
<% unless params[:experimental] %>
<h1>Listing properties</h1>

<table id="all_properties" class="table datatable table-striped table-hover table-responsive" data-source="<%= properties_url(format: "json") %>">
  <thead>
    <tr>
      <th id="all_property_nickname">Nickname</th>
      <th id="all_property_description">Description</th>
      <th id="all_property_address">Address</th>
      <th id="all_property_income">Total Income</th>
      <th id="all_property_expenses">Total Expenses</th>
      <th id="all_property_miscellaneous">Total Miscellaneous</th>
      <th id="all_property_total">Overall Total</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <!-- Look into /app/datatables/properties_datatable.rb if you need to modify the data within the table. -->
  </tbody>

  <tfoot>
    <tr>
      <th colspan="3">Total Column Sums:</th>
      <td class="text-right"><%= number_to_currency @summation[:income], :precision => 2 %></td>
      <td class="text-right"><%= number_to_currency @summation[:expense], :precision => 2 %></td>
      <td class="text-right"><%= number_to_currency @summation[:miscellaneous], :precision => 2 %></td>
      <td class="text-right"><%= number_to_currency @summation[:overall], :precision => 2 %></td>
      <th colspan="2"></th>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'New Property', new_property_path, :class => 'btn btn-large btn-primary' %>

<% else %>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Portfolio Details</h3>
      </div>
      <div class="panel-body">
        <table>
          <tbody>
            <tr>
              <th>Total Income:</th>
              <td class="text-right"><%= number_to_currency @summation[:income], :precision => 2 %></td>
            </tr>
            <tr>
              <th>Total Expense:</th>
              <td class="text-right"><%= number_to_currency @summation[:expense], :precision => 2 %></td>
            </tr>
            <tr>
              <th>Total Miscellaneous:</th>
              <td class="text-right"><%= number_to_currency @summation[:miscellaneous], :precision => 2 %></td>
            </tr>
            <tr>
              <th>Overall Total:</th>
              <td class="text-right"><%= number_to_currency @summation[:overall], :precision => 2 %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        <%= link_to 'Add Property', new_property_path, class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>

  <% @properties.each do |property| %>
      <% income = property.transactions.sum :income %>
      <% expense = property.transactions.sum :expense %>
      <% miscellaneous = property.transactions.sum :miscellaneous %>
      <% overall = (income + miscellaneous) - expense %>

      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= link_to property.nickname, property %></h3>
          </div>
          <div class="panel-body">
            <p>
              <span class="descriptor">Description:</span><br>
              <%= property.description %>
            </p>
            <p>
              <span class="descriptor">Address:</span><br>
              <%= property.address %>
            </p>
            <p>
              <span class="descriptor">Income:</span><br>
              <span class="text-right"><%= number_to_currency income, :precision => 2 %></span>
            </p>
            <p>
              <span class="descriptor">Expense:</span><br>
              <span class="text-right"><%= number_to_currency expense, :precision => 2 %></span>
            </p>
            <p>
              <span class="descriptor">Miscellaneous:</span><br>
              <span class="text-right"><%= number_to_currency miscellaneous, :precision => 2 %></span>
            </p>
            <p>
              <span class="descriptor">Overall:</span><br>
              <span class="text-right"><%= number_to_currency overall, :precision => 2 %></span>
            </p>
          </div>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_property_path(property), { :class => 'btn btn-primary btn-block' } %>
            <%= link_to 'Destroy', property, { method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-block'} %>
          </div>
        </div>
      </div>
  <% end %>
</div>

<% end %>

app/views/properties/new.html.erb
<% @title = "New Property" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New property</h1>
  </div>

  <%= render 'form' %>
</div>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to 'Back', :back %></li>
</ul>

app/views/properties/show.html.erb
<h3>Property Details <small id="notice"><%= notice %></small></h3>
<hr style="margin: 10px 0 0 0">
<div class="row">
  <div class="col-md-2">
    <strong>Nickname:</strong>
  </div>
  <div class="col-md-10">
    <%= @property.nickname %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Description:</strong>
  </div>
  <div class="col-md-10">
    <%= @property.description %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Address:</strong>
  </div>
  <div class="col-md-10">
    <%= @property.address %>
  </div>
</div>

<% if @property.transactions.length > 0 %>
    <h3>List of Transactions</h3>
    <table id="all_property_transactions" class="table datatable table-striped table-hover table-responsive" data-source="<%= property_url(format: "json") %>">
      <thead>
        <tr>
          <th id="all_property_transaction_account" class="text-capitalize"><%= :account %></th>
          <th id="all_property_transaction_date" class="text-capitalize"><%= :date %></th>
          <th id="all_property_transaction_income" class="text-capitalize"><%= :income %></th>
          <th id="all_property_transaction_expense" class="text-capitalize"><%= :expense %></th>
          <th id="all_property_transaction_miscellaneous" class="text-capitalize"><%= :miscellaneous %></th>
          <th id="all_property_transaction_comment" class="text-capitalize"><%= :comment %></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <%# render @transactions %>
      </tbody>

      <tfoot>
        <tr>
          <th colspan="2">Total Column Sum:</th>
          <td class="text-right"><%= number_to_currency @summation[:income], :precision => 2 %></td>
          <td class="text-right"><%= number_to_currency @summation[:expense], :precision => 2 %></td>
          <td class="text-right"><%= number_to_currency @summation[:miscellaneous], :precision => 2 %></td>
          <th colspan="2">Overall Total:</th>
          <td class="text-right"><%= number_to_currency @summation[:overall], :precision => 2 %></td>
        </tr>
      </tfoot>
    </table>
<% end %>

<hr style="margin: 10px 0 0 0">

<ul class="nav nav-pills navbar-left">
  <li><%= link_to "New Transaction", new_property_transaction_path(@property) %></li>
</ul>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to 'Edit', edit_property_path(@property) %></li>
  <li><%= link_to 'Back', properties_path %></li>
</ul>

app/views/transactions/_form.html.erb
<%= form_for [@transaction.property, @transaction], :html => { :class => "form-horizontal" } do |f| %>
    <% if @transaction.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

          <ul>
            <% @transaction.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="panel-body">
      <%= f.hidden_field :property_id %>
      <div class="field form-group">
        <%= f.label :account, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :account, :list => 'account-datalist', :class => 'form-control' %>
          <datalist id="account-datalist"></datalist>
        </div>
      </div>
      <div class="field form-group row">
        <%= f.label :date, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-2">
          <select class="form-control" id="transaction_date_1i" name="transaction[date(1i)]">
            <option value="">Select year</option>
            <% @possible_years.each do |year| %>
                <% if year == @current_year %>
                    <option selected="selected" value="<%= year %>"><%= year %></option>
                <% else %>
                    <option value="<%= year %>"><%= year %></option>
                <% end %>
            <% end %>
          </select>
        </div>
        <div class="col-sm-3">
          <select class="form-control" id="transaction_date_2i" name="transaction[date(2i)]">
            <option value="">Select month</option>
            <% cnt = 1 %>
            <% for month in @months_of_year %>
                <% if cnt == @current_month %>
                    <option selected="selected" value="<%= cnt %>"><%= month %></option>
                <% else %>
                    <option value="<%= cnt %>"><%= month %></option>
                <% end %>
                <% cnt += 1 %>
            <% end %>
          </select>
        </div>
        <div class="col-sm-2">
          <select class="form-control" id="transaction_date_3i" name="transaction[date(3i)]">
            <option value="">Select day</option>
            <% (1..31).each do |day| %>
                <% if day == @current_day %>
                    <option selected="selected" value="<%= day %>"><%= day %></option>
                <% else %>
                    <option value="<%= day %>"><%= day %></option>
                <% end %>
            <% end %>
          </select>
        </div>
      </div>
      
      <!--<div class="field form-group">-->
        <!--<%# f.label :date, :class => 'col-sm-2 control-label' %>-->
        <!--<div class="col-sm-10">-->
          <!--<%# f.date_select :date, :class => 'form-control' %>-->
        <!--</div>-->
      <!--</div>-->
      <div class="field form-group">
        <%= f.label :income, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :income, :class => 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :expense, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :expense, :class => 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :miscellaneous, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :miscellaneous, :class => 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :comment, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :comment, :class => 'form-control' %>
        </div>
      </div>
    </div>

    <div class="panel-footer">
      <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit nil, { :class => 'btn btn-primary' } %>
        </div>
      </div>
    </div>
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= link_to transaction.account, [transaction.property, transaction] %></td>
  <td><%= transaction.date %></td>
  <td class="text-right"><%= number_to_currency transaction.income, :precision => 2 %></td>
  <td class="text-right"><%= number_to_currency transaction.expense, :precision => 2 %></td>
  <td class="text-right"><%= number_to_currency transaction.miscellaneous, :precision => 2 %></td>
  <td><%= transaction.comment %></td>
  <td><%= link_to 'Edit', edit_property_transaction_path(transaction.property, transaction) %></td>
  <td><%= link_to 'Destroy', [transaction.property, transaction], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/transactions/edit.html.erb
<% @title = "Edit Transaction" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Editing transaction</h1>
  </div>

  <%= render 'form' %>
</div>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to 'Back', :back %></li>
</ul>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Account</th>
      <th>Date</th>
      <th>Income</th>
      <th>Expense</th>
      <th>Miscellaneous</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.property %></td>
        <td><%= transaction.account %></td>
        <td><%= transaction.date %></td>
        <td><%= transaction.income %></td>
        <td><%= transaction.expense %></td>
        <td><%= transaction.miscellaneous %></td>
        <td><%= transaction.comment %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<% @title = "New Transaction" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New transaction</h1>
  </div>

  <%= render 'form' %>
</div>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to "Back", :back %></li>
</ul>

app/views/transactions/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to @transaction.property.nickname, @transaction.property %></li>
  <li class="active"><%= @transaction.account %></li>
</ol>

<h3>Transaction Details <small id="notice"><%= notice %></small></h3>
<hr style="margin: 10px 0 0 0">

<div class="row">
  <div class="col-md-2">
    <strong>Account:</strong>
  </div>
  <div class="col-md-10">
    <%= @transaction.account %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Date:</strong>
  </div>
  <div class="col-md-10">
    <%= @transaction.date %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Income:</strong>
  </div>
  <div class="col-md-10">
    <%= number_to_currency @transaction.income, :precision => 2 %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Expense:</strong>
  </div>
  <div class="col-md-10">
    <%= number_to_currency @transaction.expense, :precision => 2 %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Miscellaneous:</strong>
  </div>
  <div class="col-md-10">
    <%= number_to_currency @transaction.miscellaneous, :precision => 2 %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <strong>Comment:</strong>
  </div>
  <div class="col-md-10">
    <%= @transaction.comment %>
  </div>
</div>

<ul class="nav nav-pills navbar-right">
  <li><%= link_to 'Edit', edit_property_transaction_path(@transaction.property, @transaction) %></li>
  <li><%= link_to 'Back', :back %></li>
</ul>